#!/bb/ash
. /etc/init.d/tc-functions

PATH="/bb:/bin:/sbin:/usr/bin:/usr/sbin"
export PATH

[ -n "$1" ] || exit 1
DEVINFO="$(blkid -s LABEL $1)"
[ -z "$DEVINFO" ] && exit 1

LABEL="${DEVINFO##*LABEL=}"
LABEL="$(echo "$LABEL"|tr -d '"')"
echo "$LABEL"
