#!/bb/ash
. /etc/init.d/tc-functions


PATH="/bb:/bin:/sbin:/usr/bin:/usr/sbin"
export PATH

#
# Fake history command for Ash.
#

cat $HOME/.ash_history 2>/dev/null || echo "No history file found..."
