// generated by Fast Light User Interface Designer (fluid) version 1.0110

#include <libintl.h>
#include "sce-tools.h"
// (c) Jason Williams 2015
#include <cstdlib>
#include <iostream>
#include <locale.h>
using namespace std;

void btn_callback(Fl_Widget* w, void* userdata) {
  system((const char*)userdata);
}

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  setlocale(LC_ALL, "");
bindtextdomain("tinycore","/usr/local/share/locale");
textdomain("tinycore");
  { Fl_Double_Window* o = new Fl_Double_Window(295, 150, gettext("SCE Tools"));
    w = o;
    { Fl_Box* o = new Fl_Box(5, 18, 140, 123);
      o->box(FL_EMBOSSED_FRAME);
      o->align(FL_ALIGN_TOP);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(150, 18, 140, 123);
      o->box(FL_EMBOSSED_FRAME);
      o->align(FL_ALIGN_TOP);
    } // Fl_Box* o
    { Fl_Button* o = new Fl_Button(15, 30, 120, 30, gettext("sce-import"));
      o->callback((Fl_Callback*)btn_callback, (void*)("aterm -bg black +sb -T \"Import SCE Extensions\" -e /usr/bin/sce-import &"));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(160, 30, 120, 30, gettext("sce-update"));
      o->callback((Fl_Callback*)btn_callback, (void*)("aterm -bg black +sb -T \"Update SCE Extensions\" -e /usr/bin/sce-update &"));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(15, 65, 120, 30, gettext("sce-load"));
      o->callback((Fl_Callback*)btn_callback, (void*)("aterm -bg black +sb -T \"Load SCE Extensions\" -e /usr/bin/sce-load &"));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(160, 65, 120, 30, gettext("sce-remove"));
      o->callback((Fl_Callback*)btn_callback, (void*)("aterm -bg black +sb -T \"Uninstall SCE Extensions\" -e /usr/bin/sce-remove &"));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(15, 100, 120, 30, gettext("sce-debpurge"));
      o->callback((Fl_Callback*)btn_callback, (void*)("aterm -bg black +sb -T \"Remove Stale Debian Packages From Storage.\" -e /usr/bin/sce-debpurge &"));
    } // Fl_Button* o
    o->end();
  } // Fl_Double_Window* o
  w->show(argc, argv);
  return Fl::run();
}
