#!/bb/ash
PATH="/bb:/bin:/sbin:/usr/bin:/usr/sbin"
export PATH
. /etc/init.d/tc-functions
if [ -f /var/log/autologin ] ; then
    exec /bb/getty 38400 tty1
else
    /bb/touch /var/log/autologin
    exec /bb/login -f root
fi
