#!/bb/ash
# RC Script for Tiny Core Linux
# (c) Robert Shingledecker 2004-2012

# Mount /proc.
[ -f /proc/cmdline ] || /bb/mount /proc

# Remount rootfs rw.
/bb/mount -o remount,rw /

# Mount system devices from /etc/fstab.
/bb/mount -a

/etc/init.d/tc-config

