#!/bb/ash

[ -e /dev/pts ] || mkdir -m 0755 /dev/pts
[ -e /dev/shm ] || mkdir -m 1777 /dev/shm

mount -t devpts devpts /dev/pts -o mode=0620,gid=5,nosuid,noexec

mount -t tmpfs shm /dev/shm -o mode=1777,nosuid,nodev