// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef swapfile_h
#define swapfile_h
#include <FL/Fl.H>
char * mygettext(const char *msgid);
void btn_callback(Fl_Widget*, void* userdata);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
extern Fl_Input *inp_mount;
extern Fl_Input *inp_size;
#include <FL/Fl_Button.H>
#endif
