// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef cpanel_h
#define cpanel_h
#include <FL/Fl.H>
void btn_callback(Fl_Widget* w, void* userdata);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
extern Fl_Button *btnWbarConf;
#endif
